### ISSUE TITLE
Валидация

### ISSUE THREAD

**Issue by casa7x** [Tatsianazhylevich/Lesson-13#1]
https://github.com/Tatsianazhylevich/Lesson-13/blob/c40cba2a3eb78240a5cf5d1fb3de7e927c2a5f5c/script.js#L27

А сделай валидацию на то, что если пользователь ввёл первое число больше чем второе, то ему выводится сообщение с каким-нибудь предупреждением. ЧТобы не плодить циклы на все чихи, давай лучше работать только с восходящим диапазоном

**Comment by Tatsianazhylevich** [comment]
Done
